name: "test"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # allow running manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - uses: ./
    - run: echo $BRANCH_NAME
